
hard_tabs = true
tab_spaces = 4
use_field_init_shorthand = true
newline_style = "Unix"
max_width = 120
use_small_heuristics = "Max"

# unstable flags
overflow_delimited_expr = true
wrap_comments = true
